[package]
name = "keyrun"
version = "0.1.0"
edition = "2024"
description = "linux keybased app launcher"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
configfs = { version = "0.1.2", features = ["system-dirs"] }
evdev = "0.13.2"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
